# Generated by Django 4.1.5 on 2023-01-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preson',
            old_name='positon',
            new_name='position',
        ),
    ]
